"""empty message

Revision ID: c5dab15a8a42
Revises: d77bb5fc0603
Create Date: 2022-09-29 22:50:52.613773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dab15a8a42'
down_revision = 'd77bb5fc0603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('friday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('monday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('saturday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('sunday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('thursday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('tuesday', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('wednesday', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'wednesday')
    op.drop_column('programs', 'tuesday')
    op.drop_column('programs', 'thursday')
    op.drop_column('programs', 'sunday')
    op.drop_column('programs', 'saturday')
    op.drop_column('programs', 'monday')
    op.drop_column('programs', 'friday')
    # ### end Alembic commands ###
